sudo: required
services:
    - docker

before_install:
    - docker build -t nikeshkamble25/multi-container-client-dev -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true nikeshkamble25/multi-container-client-dev npm run test -- --coverage

after_success:
    - docker build -t nikeshkamble25/multi-container-client ./client
    - docker build -t nikeshkamble25/multi-container-nginx ./nginx
    - docker build -t nikeshkamble25/multi-container-server ./server
    - docker build -t nikeshkamble25/multi-container-worker ./worker
#Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Take those images and push to dockerhub
    - docker push nikeshkamble25/multi-container-client
    - docker push nikeshkamble25/multi-container-nginx
    - docker push nikeshkamble25/multi-container-server
    - docker push nikeshkamble25/multi-container-worker